# Generated by Django 4.1.7 on 2023-03-30 14:18

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers
import utilities.json


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0092_delete_jobresult'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('netbox_secrets', '0007_alter_secret_assigned_object_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                (
                    'custom_field_data',
                    models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
                ),
                ('assigned_object_id', models.PositiveIntegerField()),
                ('name', models.CharField(blank=True, max_length=100)),
                ('ciphertext', models.BinaryField(max_length=65568)),
                ('hash', models.CharField(editable=False, max_length=128)),
            ],
            options={
                'ordering': ('role', 'name', 'pk'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='secret',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='secret',
            name='role',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='netbox_secrets.secretrole'
            ),
        ),
        migrations.AddConstraint(
            model_name='secret',
            constraint=models.UniqueConstraint(
                fields=('assigned_object_type', 'assigned_object_id', 'role', 'name'),
                name='netbox_secrets_secret_object_role_name',
                violation_error_message='Secrets must have a unique name within a given object and role.',
            ),
        ),
        migrations.AddField(
            model_name='certificate',
            name='assigned_object_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='role',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to='netbox_secrets.secretrole'
            ),
        ),
        migrations.AddField(
            model_name='certificate',
            name='tags',
            field=taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag'),
        ),
        migrations.AddConstraint(
            model_name='certificate',
            constraint=models.UniqueConstraint(
                fields=('assigned_object_type', 'assigned_object_id', 'role', 'name'),
                name='netbox_secrets_certificate_object_role_name',
                violation_error_message='Certificates must have a unique name within a given object and role.',
            ),
        ),
    ]
